<?php
//$title = 'My albums';
//$this->headTitle($title);
//?>
<!--<h1>--><?php //echo $this->escapeHtml($title); ?><!--</h1>-->
<!--<p>-->
<!--    <a href="--><?php //echo $this->url('album', array('action'=>'add'));?><!--">Add new album</a>-->
<!--</p>-->

<table class="table">
    <tr>
        <th>FirstName</th>
        <th>LastName</th>
        <th>PhoneNumber</th>
        <th>PostalCode</th>
        <th>City</th>
        <th>Street</th>
        <th>NumberStreet</th>
<!--        <th>&nbsp;</th>-->
    </tr>
    <?php foreach ($formulaires as $formulaire) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($formulaire->FirstName);?></td>
            <td><?php echo $this->escapeHtml($formulaire->LastName);?></td>
            <td><?php echo $this->escapeHtml($formulaire->PhoneNumber);?></td>
            <td><?php echo $this->escapeHtml($formulaire->City);?></td>
            <td><?php echo $this->escapeHtml($formulaire->Street);?></td>
            <td><?php echo $this->escapeHtml($formulaire->NumberStreet);?></td>
        </tr>
    <?php endforeach; ?>
</table>
<p>
    <a href="<?php echo $this->url('formulaire', array('action'=>'insert')); ?>">Formulaire</a>
</p>
