<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th class="th">Title</th>
        <th>Artist</th>
        <th>Email</th>
        <th>Username</th>
        <th>Language</th>
        <th>Comment</th>
        <th>Date</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr class="tr">
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td><?php echo $this->escapeHtml($album->email);?></td>
            <td><?php echo $this->escapeHtml($album->username);?></td>
            <td><?php echo $this->escapeHtml($album->language);?></td>
            <td><?php echo $this->escapeHtml($album->comment);?></td>
            <td><?php echo $this->escapeHtml($album->date);?></td>
                        <td>
                            <a href="<?php echo $this->url('album',
                                array('action'=>'edit', 'id' => $album->id));?>">Edit |</a>
                            <a href="<?php echo $this->url('album',
                                array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
                        </td>
        </tr>
    <?php endforeach; ?>
</table>
<p>
<!--    <a href="--><?php //echo $this->url('album', array('action'=>'insert')); ?><!--">Formulaire</a>-->
</p>