<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#btn1").click(function(){
                alert("Connect into your account more infos.");
            });
        });
    </script>
</head>
<body>
<p>This is a paragraph.</p>
<p>This is another paragraph.</p>

<div class="btn-group">
    <a class ="btn dropdown-toggle" data-toogle="dropdown" href="index.phtml">
        Select your action
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">

    </ul>

</div>





</body>
</html>