<?php
/**
 * Created by PhpStorm.
 * User: my1-asus
 * Date: 12/4/15
 * Time: 10:35 AM
 */
//\Zend\Debug\Debug::dump($form);
$title = 'Register Form';
$this -> headTitle($title);
?>
<!--<script src='https://www.google.com/recaptcha/api.js'></script>-->
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'register', )));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username')) ;
echo "<hr>";
echo $this->formRow($form->get('email'));
echo "<hr>";
echo $this->formRow($form->get('password'));
echo "<hr>";
echo $this->formRow($form->get('confirmPassword'));
echo "<hr>";
echo $this->formRow($form->get('date'));
echo "<hr>";

//echo $this->formRow($form->get('captcha'));
//echo '<div class="g-recaptcha" data-sitekey="6LcakRITAAAAAM0-wq5P4hIkruKxPzON7cOoXG01"></div>';
echo "<hr>";
echo $this->formHidden($form->get('my-hidden-field'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();

$form = new \Album\Form\RegisterForm();
